apiVersion: v2
name: hapi-fhir-jpaserver
description: A Helm chart for deploying the HAPI FHIR JPA server starter on Kubernetes.
type: application
home: https://github.com/hapifhir/hapi-fhir-jpaserver-starter
sources:
  - https://github.com/hapifhir/hapi-fhir-jpaserver-starter
dependencies:
  - name: postgresql
    version: 11.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
appVersion: v6.0.1
version: 0.9.0
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed, and security.
    - kind: changed
      description: |
        BREAKING CHANGE: updated HAPI FHIR starter image to v6.0.1.
        See <https://github.com/hapifhir/hapi-fhir/releases/tag/v6.0.0> for all application changes.
    - kind: changed
      description: |
        updated included PostgreSQL-subchart to v11.6.2
    - kind: fixed
      description: |
        use a fixed image for the wait-for-database container (docker.io/bitnami/postgresql:14.3.0-debian-10-r20)
        instead of relying on the PostgreSQL sub-chart values
    - kind: changed
      description: |
        expose actuator/metrics endpoint on a separate port (8081)
    - kind: added
      description: |
        support for monitoring metrics using ServiceMonitor CRDs
    - kind: changed
      description: |
        switched liveness and readiness probes to Spring Boot actuator endpoints
    - kind: changed
      description: |
        BREAKING CHANGE: removed included `NetworkPolicy`, which is subject to more thorough rework
    - kind: added
      description: |
        allow configuring `topologySpreadConstraints` for the deployment
